version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
leavesCullingMode = "DEPTH"
leavesCullingAmount = 3
includeMangroveRoots = true
powderSnowCulling = true
endGatewayCulling = true
beaconBeamCulling = true
entityModelCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
candlelight = true
azurelib = true
elemental_metals = true
tide = true
bountiful = true
mythicmobs = true
alloy_forgery = true
doapi = true
spectrum = true
nebulus_cherry_blossem_tree = true
betternether = true
rsjukeboxes = true
brewery = true
urkazmoontools = true
ribbits = true
dungeonnowloading = true
betterend = true
runes = true
ecologics = true
libraryferret = true
furniture = true
usefulbackpacks = true
aquamirae = true
duckling = true
yigd = true
mcwbridges = true
aether = true
mcwlights = true
bloomingnature = true
majruszsdifficulty = true
ftbquests = true
bakery = true
graveyard = true
customportalapi = true
spell_engine = true
knightlib = true
naturalist = true
kubejs = true
minecells = true
supplementaries = true
deeperdarker = true
paladins = true
endrem = true
sawmill = true
yungscavebiomes = true
items_displayed = true
transmog = true
ironchest = true
rogues = true
philipsruins = true
minecraft = true
animal_feeding_trough = true
enderzoology = true
fwaystones = true
regions_unexplored = true
betterarcheology = true
wetlands = true
knightquest = true
fleshz = true
jewelry = true
adventurez = true
bosses_of_mass_destruction = true
decorative_blocks = true
archers = true
vinery = true
enchantinginfuser = true
illagerinvasion = true
